language: node_js
node_js:
- '10'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: dD94NPeVA7BXfJEcGFImlSb+hidT1u8kGhhSXpUED/6iLPUVZZxo77ufTyvxlk2MYfjHSKG84nFDXdZ2UyGhtv+O+cnhNumohV1RWnSnv/SqSfEjWJoNxI5+HkYO77YIibBWenMG49Ozu6LEl64ZY0TtE83HCSWI/RdYk06r3i7gDtscGNPvMx/eaWKkKpwhixG8ICmLhAFkUlMhMYjkWalF8P+zU7xZ2K5f5EimmBsG3+2uCEEkvYV6e+1tW6ntibfu0Ui1ObqMtG+B7ziBJIrdWceOjQZ+/5TynbCWrGv2YrMm+X2/5a4saKlfho9QuUdZkN61Wem81xY6qHE1rQf9rwZoILz6327ZGnO+Q1mgij+Xr8vKVnqszKxZ79c8tl3zoggd9b/+Be61g3v65QsC4o1gamKntnG0eO1K7q8n//1w+UGsIuN6vcc2qqt4vDAMXpnTZcQN8FUnxtkddFbrO0tt6FClF37DD2cUwPjnceciJgztFlH4xwiHf0Uaq8EsWi2Z0xWoOPm/I1NO/qmz2G/GtTJdDZcJcqMEG2+PsjahXQClKaPTR9wOgbyf47xr3kIfaLiv/pZweL/FL8d4mQABqNpadtXt5brUo/HBWv6DUA8JFJxjKfn7EVz3a1Tt2HjMtACdUD3vBtpy5zx1iV9tbwyAh3DpE8Z69Ds=
  skip_cleanup: true
  on:
    tags: true
    branch: master
