language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: lTQ/SEUKXjmzqwwEJRQLTPe+Qcf4vta3g5LXHxL3357JGrHYKGxvDsc29cbryqdyupEgyLPw7XZIAeqGcTw4Idivmo2PFc6loogEsblAL+YnJ7/ca179nLDPK/37fA1gBFQL2Z35eNR9WyTt1/AiAxCs3y4tz8PkCUN2ld4jZUYGtiR8lp1Qf/5SXIIup2pkqQOtIoscfKx3F0QZneG5O0uVy8iRfMZrfH1XeZssMf9+kDa6TL+SifN/fquKZHPqO6TVV1UaZxGjBAl+cOItD0Bv4gpcZvJ4bf0PdvfJ6bRziro9E3pUvAN+SN52wDZMutSH10sAkMCCzMWAnwHfds5cfD3HEZXtMetb6JJauqllMe/yhQ2A0ivrx1KCrhFDib9muCF0504EvoLzULtvdxMOQbL6U2fJ8sU4fPtr92XT0kKd+FPO81d51LsmTZpzEvGn+VqP3YbHTKMcba52IAkYgo96yBHsQYRtmv7vZjaIItDvFOQ9UCLLQGt3FM+sl6xOO8mGOm+4otiJ4Vz5SoLVygY7iHtRn13e7uyM5etDpy2KaSrdyviAtz/Y/iieh/ATTqVVDFX4ab4xkXkQpGnRGTOLte3Z7VDU/NQmaybwAVXmcbIMS+OVFdVXpjEL0EALTk73NB58abHUZM3zuPUJyhdtDdGfVUrnfR1BiHU=
  skip_cleanup: true
  on:
    tags: true
    branch: master
